<?php

use Illuminate\Database\Seeder;

class MachineTagsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	DB::table('machine_tags')->delete();

        $machine_tags = [
            [ 'name' => 'Capacity Utilization', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 2, 'type' => 'line', 'offset' => 0, 'divided_by' => 10 ],
            [ 'name' => 'Energy Consumption', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 3, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Blender Capability', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 17, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Process Rate', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 18, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Load cell A zero bits', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 20, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Load cell A cal bits', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 21, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Load cell B zero bits', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 22, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Load cell B cal bits', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 23, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Weigh hopper tare', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 24, 'type' => 'line', 'offset' => 0, 'divided_by' => 1000 ],
            [ 'name' => 'Target Weight[1]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 13, 'type' => 'line', 'offset' => 0, 'divided_by' => 1000 ],
            [ 'name' => 'Target Weight[2]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 13, 'type' => 'line', 'offset' => 1, 'divided_by' => 1000 ],
            [ 'name' => 'Target Weight[3]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 13, 'type' => 'line', 'offset' => 2, 'divided_by' => 1000 ],
            [ 'name' => 'Target Weight[4]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 13, 'type' => 'line', 'offset' => 3, 'divided_by' => 1000 ],
            [ 'name' => 'Target Weight[5]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 13, 'type' => 'line', 'offset' => 4, 'divided_by' => 1000 ],
            [ 'name' => 'Target Weight[6]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 13, 'type' => 'line', 'offset' => 5, 'divided_by' => 1000 ],
            [ 'name' => 'Target Weight[7]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 13, 'type' => 'line', 'offset' => 6, 'divided_by' => 1000 ],
            [ 'name' => 'Target Weight[8]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 13, 'type' => 'line', 'offset' => 7, 'divided_by' => 1000 ],
            [ 'name' => 'Actual Weight[1]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 14, 'type' => 'line', 'offset' => 0, 'divided_by' => 1000 ],
            [ 'name' => 'Actual Weight[2]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 14, 'type' => 'line', 'offset' => 1, 'divided_by' => 1000 ],
            [ 'name' => 'Actual Weight[3]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 14, 'type' => 'line', 'offset' => 2, 'divided_by' => 1000 ],
            [ 'name' => 'Actual Weight[4]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 14, 'type' => 'line', 'offset' => 3, 'divided_by' => 1000 ],
            [ 'name' => 'Actual Weight[5]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 14, 'type' => 'line', 'offset' => 4, 'divided_by' => 1000 ],
            [ 'name' => 'Actual Weight[6]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 14, 'type' => 'line', 'offset' => 5, 'divided_by' => 1000 ],
            [ 'name' => 'Actual Weight[7]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 14, 'type' => 'line', 'offset' => 6, 'divided_by' => 1000 ],
            [ 'name' => 'Actual Weight[8]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 14, 'type' => 'line', 'offset' => 7, 'divided_by' => 1000 ],
            [ 'name' => 'Calibration Factor[1]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 0, 'divided_by' => 100 ],
            [ 'name' => 'Calibration Factor[2]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 1, 'divided_by' => 100 ],
            [ 'name' => 'Calibration Factor[3]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 2, 'divided_by' => 100 ],
            [ 'name' => 'Calibration Factor[4]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 3, 'divided_by' => 100 ],
            [ 'name' => 'Calibration Factor[5]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 4, 'divided_by' => 100 ],
            [ 'name' => 'Calibration Factor[6]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 5, 'divided_by' => 100 ],
            [ 'name' => 'Calibration Factor[7]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 6, 'divided_by' => 100 ],
            [ 'name' => 'Calibration Factor[8]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 7, 'divided_by' => 100 ],
            [ 'name' => 'Hopper Stable[1]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 25, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Hopper Stable[2]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 25, 'type' => 'line', 'offset' => 1, 'divided_by' => 1 ],
            [ 'name' => 'Hopper Stable[3]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 25, 'type' => 'line', 'offset' => 2, 'divided_by' => 1 ],
            [ 'name' => 'Hopper Stable[4]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 25, 'type' => 'line', 'offset' => 3, 'divided_by' => 1 ],
            [ 'name' => 'Hopper Stable[5]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 25, 'type' => 'line', 'offset' => 4, 'divided_by' => 1 ],
            [ 'name' => 'Hopper Stable[6]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 25, 'type' => 'line', 'offset' => 5, 'divided_by' => 1 ],
            [ 'name' => 'Hopper Stable[7]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 25, 'type' => 'line', 'offset' => 6, 'divided_by' => 1 ],
            [ 'name' => 'Hopper Stable[8]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 25, 'type' => 'line', 'offset' => 7, 'divided_by' => 1 ],

            [ 'name' => 'Capacity Utilization', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 2, 'type' => 'line', 'offset' => 0, 'divided_by' => 10 ],
            [ 'name' => 'Energy Consumption', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 3, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Current Recipe[1]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 3, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Current Recipe[2]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 3, 'type' => 'line', 'offset' => 1, 'divided_by' => 1 ],
            [ 'name' => 'Current Recipe[3]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 3, 'type' => 'line', 'offset' => 2, 'divided_by' => 1 ],
            [ 'name' => 'Current Recipe[4]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 3, 'type' => 'line', 'offset' => 3, 'divided_by' => 1 ],
            [ 'name' => 'Current Recipe[5]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 3, 'type' => 'line', 'offset' => 4, 'divided_by' => 1 ],
            [ 'name' => 'Current Recipe[6]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 3, 'type' => 'line', 'offset' => 5, 'divided_by' => 1 ],
            [ 'name' => 'Actual Recipe[1]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 12, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Actual Recipe[2]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 13, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Actual Recipe[3]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 14, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Actual Recipe[4]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 15, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Actual Recipe[5]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 16, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Actual Recipe[6]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 17, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Current Target Rate', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 18, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Speed[1]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Speed[2]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 1, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Speed[3]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 2, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Speed[4]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 3, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Speed[5]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 4, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Speed[6]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 5, 'divided_by' => 1 ],
            [ 'name' => 'Accumulated Hopper Inventory[1]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 20, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Accumulated Hopper Inventory[2]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 20, 'type' => 'line', 'offset' => 1, 'divided_by' => 1 ],
            [ 'name' => 'Accumulated Hopper Inventory[3]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 20, 'type' => 'line', 'offset' => 2, 'divided_by' => 1 ],
            [ 'name' => 'Accumulated Hopper Inventory[4]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 20, 'type' => 'line', 'offset' => 3, 'divided_by' => 1 ],
            [ 'name' => 'Accumulated Hopper Inventory[5]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 20, 'type' => 'line', 'offset' => 4, 'divided_by' => 1 ],
            [ 'name' => 'Accumulated Hopper Inventory[6]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 20, 'type' => 'line', 'offset' => 5, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Calibration[1]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 21, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Calibration[2]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 21, 'type' => 'line', 'offset' => 1, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Calibration[3]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 21, 'type' => 'line', 'offset' => 2, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Calibration[4]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 21, 'type' => 'line', 'offset' => 3, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Calibration[5]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 21, 'type' => 'line', 'offset' => 4, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Calibration[6]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 21, 'type' => 'line', 'offset' => 5, 'divided_by' => 1 ],
            [ 'name' => 'Blender Capability', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 22, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Process Rate', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 23, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'System Steady', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 24, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Massflow Hopper Stable', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 25, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Stable[1]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 26, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Stable[2]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 26, 'type' => 'line', 'offset' => 1, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Stable[3]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 26, 'type' => 'line', 'offset' => 2, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Stable[4]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 26, 'type' => 'line', 'offset' => 3, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Stable[5]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 26, 'type' => 'line', 'offset' => 4, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Stable[6]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 26, 'type' => 'line', 'offset' => 5, 'divided_by' => 1 ],
            [ 'name' => 'Extruder wtp/rpm stable', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 27, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],

            [ 'name' => 'Capacity Utilization', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 2, 'type' => 'line', 'offset' => 0, 'divided_by' => 10 ],
            [ 'name' => 'Energy Consumption', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 3, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Hauloff Enabled', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 32, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Extruder Rpm setpoint', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 13, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'extruder rpm actual', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 14, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'extruder target throughput', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 15, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'extruder actual throughput', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 16, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'extruder wtp/rpm value', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 17, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'hauloff setpoint', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 18, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'hauloff actual', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 19, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'accumulated hopper inventory', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 23, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'accumulated hauloff length', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 24, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'system steady', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 25, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'wtp stable', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 26, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'extruder rpm stable', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 27, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'hauloff stable', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 28, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Hopper Dumping', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 29, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Recipe Setpoint', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 20, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Recipe Actual point', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 21, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],

            [ 'name' => 'Capacity Utilization', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 2, 'type' => 'line', 'offset' => 0, 'divided_by' => 10 ],
            [ 'name' => 'Energy Consumption', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 3, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'feeder rpm setpoint', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 11, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'tracking extruder rpm', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 12, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'tracking extruder max rpm', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 13, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'tracking extruder wtp', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 14, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'feeder target throughput', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 15, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'feeder actual throughput', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 16, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'feeder wtp/rpm value', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 17, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'recipe setpoint', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 18, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'recipe actual', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'accumulated hopper inventory', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 20, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'system steady', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 21, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'wtp stable', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 22, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'feeder rpm stable', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 23, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'hopper dumping', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 24, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],

            [ 'name' => 'Capacity Utilization', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 2, 'type' => 'line', 'offset' => 0, 'divided_by' => 10 ],
            [ 'name' => 'Energy Consumption', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 3, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 15, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 15, 'type' => 'line', 'offset' => 1, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 15, 'type' => 'line', 'offset' => 2, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 15, 'type' => 'line', 'offset' => 3, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 15, 'type' => 'line', 'offset' => 4, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 15, 'type' => 'line', 'offset' => 5, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 15, 'type' => 'line', 'offset' => 6, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 15, 'type' => 'line', 'offset' => 7, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 15, 'type' => 'line', 'offset' => 8, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 15, 'type' => 'line', 'offset' => 9, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 15, 'type' => 'line', 'offset' => 10, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 15, 'type' => 'line', 'offset' => 11, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Between Oil Changes', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 16, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Between Oil Changes', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 16, 'type' => 'line', 'offset' => 1, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Between Oil Changes', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 16, 'type' => 'line', 'offset' => 2, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Between Oil Changes', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 16, 'type' => 'line', 'offset' => 3, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Between Oil Changes', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 16, 'type' => 'line', 'offset' => 4, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Between Oil Changes', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 16, 'type' => 'line', 'offset' => 5, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Between Oil Changes', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 16, 'type' => 'line', 'offset' => 6, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Between Oil Changes', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 16, 'type' => 'line', 'offset' => 7, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Between Oil Changes', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 16, 'type' => 'line', 'offset' => 8, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Between Oil Changes', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 16, 'type' => 'line', 'offset' => 9, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Between Oil Changes', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 16, 'type' => 'line', 'offset' => 10, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Between Oil Changes', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 16, 'type' => 'line', 'offset' => 11, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Oil Change Target', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 17, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Oil Change Target', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 17, 'type' => 'line', 'offset' => 1, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Oil Change Target', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 17, 'type' => 'line', 'offset' => 2, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Oil Change Target', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 17, 'type' => 'line', 'offset' => 3, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Oil Change Target', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 17, 'type' => 'line', 'offset' => 4, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Oil Change Target', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 17, 'type' => 'line', 'offset' => 5, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Oil Change Target', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 17, 'type' => 'line', 'offset' => 6, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Oil Change Target', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 17, 'type' => 'line', 'offset' => 7, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Oil Change Target', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 17, 'type' => 'line', 'offset' => 8, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Oil Change Target', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 17, 'type' => 'line', 'offset' => 9, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Oil Change Target', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 17, 'type' => 'line', 'offset' => 10, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Oil Change Target', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 17, 'type' => 'line', 'offset' => 11, 'divided_by' => 1 ],
            [ 'name' => 'ump Blowback Engaged', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 14, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Pump Blowback Engaged', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 14, 'type' => 'line', 'offset' => 1, 'divided_by' => 1 ],
            [ 'name' => 'Pump Blowback Engaged', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 14, 'type' => 'line', 'offset' => 2, 'divided_by' => 1 ],
            [ 'name' => 'Pump Blowback Engaged', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 14, 'type' => 'line', 'offset' => 3, 'divided_by' => 1 ],
            [ 'name' => 'Pump Blowback Engaged', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 14, 'type' => 'line', 'offset' => 4, 'divided_by' => 1 ],
            [ 'name' => 'Pump Blowback Engaged', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 14, 'type' => 'line', 'offset' => 5, 'divided_by' => 1 ],
            [ 'name' => 'Pump Blowback Engaged', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 14, 'type' => 'line', 'offset' => 6, 'divided_by' => 1 ],
            [ 'name' => 'Pump Blowback Engaged', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 14, 'type' => 'line', 'offset' => 7, 'divided_by' => 1 ],
            [ 'name' => 'Pump Blowback Engaged', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 14, 'type' => 'line', 'offset' => 8, 'divided_by' => 1 ],
            [ 'name' => 'Pump Blowback Engaged', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 14, 'type' => 'line', 'offset' => 9, 'divided_by' => 1 ],
            [ 'name' => 'Pump Blowback Engaged', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 14, 'type' => 'line', 'offset' => 10, 'divided_by' => 1 ],
            [ 'name' => 'pump blowback engaged', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 14, 'type' => 'line', 'offset' => 11, 'divided_by' => 1 ],
            [ 'name' => 'pump blowback engaged', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 14, 'type' => 'line', 'offset' => 1, 'divided_by' => 1 ],
            [ 'name' => 'Pump Online', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 12, 'type' => 'line', 'offset' => 2, 'divided_by' => 1 ],
            [ 'name' => 'Pump Online', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 12, 'type' => 'line', 'offset' => 3, 'divided_by' => 1 ],
            [ 'name' => 'Pump Online', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 12, 'type' => 'line', 'offset' => 4, 'divided_by' => 1 ],
            [ 'name' => 'Pump Online', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 12, 'type' => 'line', 'offset' => 5, 'divided_by' => 1 ],
            [ 'name' => 'Pump Online', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 12, 'type' => 'line', 'offset' => 6, 'divided_by' => 1 ],
            [ 'name' => 'Pump Online', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 12, 'type' => 'line', 'offset' => 7, 'divided_by' => 1 ],
            [ 'name' => 'Pump Online', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 12, 'type' => 'line', 'offset' => 8, 'divided_by' => 1 ],
            [ 'name' => 'Pump Online', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 12, 'type' => 'line', 'offset' => 9, 'divided_by' => 1 ],
            [ 'name' => 'Pump Online', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 12, 'type' => 'line', 'offset' => 10, 'divided_by' => 1 ],
            [ 'name' => 'Pump Online', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 12, 'type' => 'line', 'offset' => 11, 'divided_by' => 1 ],
            [ 'name' => 'Pumps Present', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 23, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Stations Present', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 22, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],

            [ 'name' => 'Delivery', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 2, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Mold', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 3, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Return', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 4, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Flow Value', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 5, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Setpoint 1', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 8, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Setpoint 2', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 9, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Prop. Band Heat', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 12, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Prop. Band Cool', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 13, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Delivery Temp', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 22, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Setpoint 1', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 23, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Heater Output Percent', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 28, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Cooling Output Percent', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 29, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Pump Status', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 40, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Heater Status', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 41, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Vent Status', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 42, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Proportional Percent', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 24, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Integral Percent', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 25, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Direvative Percent', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 26, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
        ];

        DB::table('machine_tags')->insert($machine_tags);
    }
}
