<?php

use Illuminate\Database\Seeder;

class MachineTagsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
    	DB::table('machine_tags')->delete();

        $machine_tags = [
            [ 'name' => 'Capacity Utilization', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 2, 'type' => 'line', 'offset' => 0, 'divided_by' => 10 ],
            [ 'name' => 'Energy Consumption', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 3, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Blender Capability', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 17, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Process Rate', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 18, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Load cell A zero bits', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 20, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Load cell A cal bits', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 21, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Load cell B zero bits', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 22, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Load cell B cal bits', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 23, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Weigh hopper tare', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 24, 'type' => 'line', 'offset' => 0, 'divided_by' => 1000 ],
            [ 'name' => 'Target Weight[1]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 13, 'type' => 'line', 'offset' => 0, 'divided_by' => 1000 ],
            [ 'name' => 'Target Weight[2]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 13, 'type' => 'line', 'offset' => 1, 'divided_by' => 1000 ],
            [ 'name' => 'Target Weight[3]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 13, 'type' => 'line', 'offset' => 2, 'divided_by' => 1000 ],
            [ 'name' => 'Target Weight[4]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 13, 'type' => 'line', 'offset' => 3, 'divided_by' => 1000 ],
            [ 'name' => 'Target Weight[5]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 13, 'type' => 'line', 'offset' => 4, 'divided_by' => 1000 ],
            [ 'name' => 'Target Weight[6]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 13, 'type' => 'line', 'offset' => 5, 'divided_by' => 1000 ],
            [ 'name' => 'Target Weight[7]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 13, 'type' => 'line', 'offset' => 6, 'divided_by' => 1000 ],
            [ 'name' => 'Target Weight[8]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 13, 'type' => 'line', 'offset' => 7, 'divided_by' => 1000 ],
            [ 'name' => 'Actual Weight[1]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 14, 'type' => 'line', 'offset' => 0, 'divided_by' => 1000 ],
            [ 'name' => 'Actual Weight[2]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 14, 'type' => 'line', 'offset' => 1, 'divided_by' => 1000 ],
            [ 'name' => 'Actual Weight[3]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 14, 'type' => 'line', 'offset' => 2, 'divided_by' => 1000 ],
            [ 'name' => 'Actual Weight[4]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 14, 'type' => 'line', 'offset' => 3, 'divided_by' => 1000 ],
            [ 'name' => 'Actual Weight[5]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 14, 'type' => 'line', 'offset' => 4, 'divided_by' => 1000 ],
            [ 'name' => 'Actual Weight[6]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 14, 'type' => 'line', 'offset' => 5, 'divided_by' => 1000 ],
            [ 'name' => 'Actual Weight[7]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 14, 'type' => 'line', 'offset' => 6, 'divided_by' => 1000 ],
            [ 'name' => 'Actual Weight[8]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 14, 'type' => 'line', 'offset' => 7, 'divided_by' => 1000 ],
            [ 'name' => 'Calibration Factor[1]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 0, 'divided_by' => 100 ],
            [ 'name' => 'Calibration Factor[2]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 1, 'divided_by' => 100 ],
            [ 'name' => 'Calibration Factor[3]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 2, 'divided_by' => 100 ],
            [ 'name' => 'Calibration Factor[4]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 3, 'divided_by' => 100 ],
            [ 'name' => 'Calibration Factor[5]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 4, 'divided_by' => 100 ],
            [ 'name' => 'Calibration Factor[6]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 5, 'divided_by' => 100 ],
            [ 'name' => 'Calibration Factor[7]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 6, 'divided_by' => 100 ],
            [ 'name' => 'Calibration Factor[8]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 7, 'divided_by' => 100 ],
            [ 'name' => 'Hopper Stable[1]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 25, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Hopper Stable[2]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 25, 'type' => 'line', 'offset' => 1, 'divided_by' => 1 ],
            [ 'name' => 'Hopper Stable[3]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 25, 'type' => 'line', 'offset' => 2, 'divided_by' => 1 ],
            [ 'name' => 'Hopper Stable[4]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 25, 'type' => 'line', 'offset' => 3, 'divided_by' => 1 ],
            [ 'name' => 'Hopper Stable[5]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 25, 'type' => 'line', 'offset' => 4, 'divided_by' => 1 ],
            [ 'name' => 'Hopper Stable[6]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 25, 'type' => 'line', 'offset' => 5, 'divided_by' => 1 ],
            [ 'name' => 'Hopper Stable[7]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 25, 'type' => 'line', 'offset' => 6, 'divided_by' => 1 ],
            [ 'name' => 'Hopper Stable[8]', 'configuration_id' => MACHINE_BD_BATCH_BLENDER, 'tag_id' => 25, 'type' => 'line', 'offset' => 7, 'divided_by' => 1 ],

            [ 'name' => 'Capacity Utilization', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 2, 'type' => 'line', 'offset' => 0, 'divided_by' => 10 ],
            [ 'name' => 'Energy Consumption', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 3, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Current Recipe[1]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 3, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Current Recipe[2]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 3, 'type' => 'line', 'offset' => 1, 'divided_by' => 1 ],
            [ 'name' => 'Current Recipe[3]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 3, 'type' => 'line', 'offset' => 2, 'divided_by' => 1 ],
            [ 'name' => 'Current Recipe[4]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 3, 'type' => 'line', 'offset' => 3, 'divided_by' => 1 ],
            [ 'name' => 'Current Recipe[5]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 3, 'type' => 'line', 'offset' => 4, 'divided_by' => 1 ],
            [ 'name' => 'Current Recipe[6]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 3, 'type' => 'line', 'offset' => 5, 'divided_by' => 1 ],
            [ 'name' => 'Actual Recipe[1]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 12, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Actual Recipe[2]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 13, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Actual Recipe[3]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 14, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Actual Recipe[4]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 15, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Actual Recipe[5]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 16, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Actual Recipe[6]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 17, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Current Target Rate', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 18, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Speed[1]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Speed[2]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 1, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Speed[3]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 2, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Speed[4]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 3, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Speed[5]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 4, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Speed[6]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 5, 'divided_by' => 1 ],
            [ 'name' => 'Accumulated Hopper Inventory[1]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 20, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Accumulated Hopper Inventory[2]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 20, 'type' => 'line', 'offset' => 1, 'divided_by' => 1 ],
            [ 'name' => 'Accumulated Hopper Inventory[3]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 20, 'type' => 'line', 'offset' => 2, 'divided_by' => 1 ],
            [ 'name' => 'Accumulated Hopper Inventory[4]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 20, 'type' => 'line', 'offset' => 3, 'divided_by' => 1 ],
            [ 'name' => 'Accumulated Hopper Inventory[5]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 20, 'type' => 'line', 'offset' => 4, 'divided_by' => 1 ],
            [ 'name' => 'Accumulated Hopper Inventory[6]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 20, 'type' => 'line', 'offset' => 5, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Calibration[1]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 21, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Calibration[2]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 21, 'type' => 'line', 'offset' => 1, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Calibration[3]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 21, 'type' => 'line', 'offset' => 2, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Calibration[4]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 21, 'type' => 'line', 'offset' => 3, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Calibration[5]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 21, 'type' => 'line', 'offset' => 4, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Calibration[6]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 21, 'type' => 'line', 'offset' => 5, 'divided_by' => 1 ],
            [ 'name' => 'Blender Capability', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 22, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Process Rate', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 23, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'System Steady', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 24, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Massflow Hopper Stable', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 25, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Stable[1]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 26, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Stable[2]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 26, 'type' => 'line', 'offset' => 1, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Stable[3]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 26, 'type' => 'line', 'offset' => 2, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Stable[4]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 26, 'type' => 'line', 'offset' => 3, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Stable[5]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 26, 'type' => 'line', 'offset' => 4, 'divided_by' => 1 ],
            [ 'name' => 'Feeder Stable[6]', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 26, 'type' => 'line', 'offset' => 5, 'divided_by' => 1 ],
            [ 'name' => 'Extruder wtp/rpm stable', 'configuration_id' => MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER, 'tag_id' => 27, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],

            [ 'name' => 'Capacity Utilization', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 2, 'type' => 'line', 'offset' => 0, 'divided_by' => 10 ],
            [ 'name' => 'Energy Consumption', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 3, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Hauloff Enabled', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 32, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Extruder Rpm setpoint', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 13, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'extruder rpm actual', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 14, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'extruder target throughput', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 15, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'extruder actual throughput', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 16, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'extruder wtp/rpm value', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 17, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'hauloff setpoint', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 18, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'hauloff actual', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 19, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'accumulated hopper inventory', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 23, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'accumulated hauloff length', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 24, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'system steady', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 25, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'wtp stable', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 26, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'extruder rpm stable', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 27, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'hauloff stable', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 28, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Hopper Dumping', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 29, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Recipe Setpoint', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 20, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Recipe Actual point', 'configuration_id' => MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER, 'tag_id' => 21, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],

            [ 'name' => 'Capacity Utilization', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 2, 'type' => 'line', 'offset' => 0, 'divided_by' => 10 ],
            [ 'name' => 'Energy Consumption', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 3, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'feeder rpm setpoint', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 11, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'tracking extruder rpm', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 12, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'tracking extruder max rpm', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 13, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'tracking extruder wtp', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 14, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'feeder target throughput', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 15, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'feeder actual throughput', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 16, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'feeder wtp/rpm value', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 17, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'recipe setpoint', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 18, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'recipe actual', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 19, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'accumulated hopper inventory', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 20, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'system steady', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 21, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'wtp stable', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 22, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'feeder rpm stable', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 23, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'hopper dumping', 'configuration_id' => MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER, 'tag_id' => 24, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],

            [ 'name' => 'Capacity Utilization', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 2, 'type' => 'line', 'offset' => 0, 'divided_by' => 10 ],
            [ 'name' => 'Energy Consumption', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 3, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 15, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 15, 'type' => 'line', 'offset' => 1, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 15, 'type' => 'line', 'offset' => 2, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 15, 'type' => 'line', 'offset' => 3, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 15, 'type' => 'line', 'offset' => 4, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 15, 'type' => 'line', 'offset' => 5, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 15, 'type' => 'line', 'offset' => 6, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 15, 'type' => 'line', 'offset' => 7, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 15, 'type' => 'line', 'offset' => 8, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 15, 'type' => 'line', 'offset' => 9, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 15, 'type' => 'line', 'offset' => 10, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 15, 'type' => 'line', 'offset' => 11, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Between Oil Changes', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 16, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Between Oil Changes', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 16, 'type' => 'line', 'offset' => 1, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Between Oil Changes', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 16, 'type' => 'line', 'offset' => 2, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Between Oil Changes', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 16, 'type' => 'line', 'offset' => 3, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Between Oil Changes', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 16, 'type' => 'line', 'offset' => 4, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Between Oil Changes', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 16, 'type' => 'line', 'offset' => 5, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Between Oil Changes', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 16, 'type' => 'line', 'offset' => 6, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Between Oil Changes', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 16, 'type' => 'line', 'offset' => 7, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Between Oil Changes', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 16, 'type' => 'line', 'offset' => 8, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Between Oil Changes', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 16, 'type' => 'line', 'offset' => 9, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Between Oil Changes', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 16, 'type' => 'line', 'offset' => 10, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Between Oil Changes', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 16, 'type' => 'line', 'offset' => 11, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Oil Change Target', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 17, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Oil Change Target', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 17, 'type' => 'line', 'offset' => 1, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Oil Change Target', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 17, 'type' => 'line', 'offset' => 2, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Oil Change Target', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 17, 'type' => 'line', 'offset' => 3, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Oil Change Target', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 17, 'type' => 'line', 'offset' => 4, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Oil Change Target', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 17, 'type' => 'line', 'offset' => 5, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Oil Change Target', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 17, 'type' => 'line', 'offset' => 6, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Oil Change Target', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 17, 'type' => 'line', 'offset' => 7, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Oil Change Target', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 17, 'type' => 'line', 'offset' => 8, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Oil Change Target', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 17, 'type' => 'line', 'offset' => 9, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Oil Change Target', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 17, 'type' => 'line', 'offset' => 10, 'divided_by' => 1 ],
            [ 'name' => 'Pump Hours Oil Change Target', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 17, 'type' => 'line', 'offset' => 11, 'divided_by' => 1 ],
            [ 'name' => 'ump Blowback Engaged', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 14, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Pump Blowback Engaged', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 14, 'type' => 'line', 'offset' => 1, 'divided_by' => 1 ],
            [ 'name' => 'Pump Blowback Engaged', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 14, 'type' => 'line', 'offset' => 2, 'divided_by' => 1 ],
            [ 'name' => 'Pump Blowback Engaged', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 14, 'type' => 'line', 'offset' => 3, 'divided_by' => 1 ],
            [ 'name' => 'Pump Blowback Engaged', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 14, 'type' => 'line', 'offset' => 4, 'divided_by' => 1 ],
            [ 'name' => 'Pump Blowback Engaged', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 14, 'type' => 'line', 'offset' => 5, 'divided_by' => 1 ],
            [ 'name' => 'Pump Blowback Engaged', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 14, 'type' => 'line', 'offset' => 6, 'divided_by' => 1 ],
            [ 'name' => 'Pump Blowback Engaged', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 14, 'type' => 'line', 'offset' => 7, 'divided_by' => 1 ],
            [ 'name' => 'Pump Blowback Engaged', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 14, 'type' => 'line', 'offset' => 8, 'divided_by' => 1 ],
            [ 'name' => 'Pump Blowback Engaged', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 14, 'type' => 'line', 'offset' => 9, 'divided_by' => 1 ],
            [ 'name' => 'Pump Blowback Engaged', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 14, 'type' => 'line', 'offset' => 10, 'divided_by' => 1 ],
            [ 'name' => 'pump blowback engaged', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 14, 'type' => 'line', 'offset' => 11, 'divided_by' => 1 ],
            [ 'name' => 'pump blowback engaged', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 14, 'type' => 'line', 'offset' => 1, 'divided_by' => 1 ],
            [ 'name' => 'Pump Online', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 12, 'type' => 'line', 'offset' => 2, 'divided_by' => 1 ],
            [ 'name' => 'Pump Online', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 12, 'type' => 'line', 'offset' => 3, 'divided_by' => 1 ],
            [ 'name' => 'Pump Online', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 12, 'type' => 'line', 'offset' => 4, 'divided_by' => 1 ],
            [ 'name' => 'Pump Online', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 12, 'type' => 'line', 'offset' => 5, 'divided_by' => 1 ],
            [ 'name' => 'Pump Online', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 12, 'type' => 'line', 'offset' => 6, 'divided_by' => 1 ],
            [ 'name' => 'Pump Online', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 12, 'type' => 'line', 'offset' => 7, 'divided_by' => 1 ],
            [ 'name' => 'Pump Online', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 12, 'type' => 'line', 'offset' => 8, 'divided_by' => 1 ],
            [ 'name' => 'Pump Online', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 12, 'type' => 'line', 'offset' => 9, 'divided_by' => 1 ],
            [ 'name' => 'Pump Online', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 12, 'type' => 'line', 'offset' => 10, 'divided_by' => 1 ],
            [ 'name' => 'Pump Online', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 12, 'type' => 'line', 'offset' => 11, 'divided_by' => 1 ],
            [ 'name' => 'Pumps Present', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 23, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Stations Present', 'configuration_id' => MACHINE_VTC_PLUS_CONVEYING_SYSTEM, 'tag_id' => 22, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],

            [ 'name' => 'Delivery', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 2, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Mold', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 3, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Return', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 4, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Flow Value', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 5, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Setpoint 1', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 8, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Setpoint 2', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 9, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Prop. Band Heat', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 12, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Prop. Band Cool', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 13, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Delivery Temp', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 22, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Setpoint 1', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 23, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Heater Output Percent', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 28, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Cooling Output Percent', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 29, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Pump Status', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 40, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Heater Status', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 41, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Vent Status', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 42, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Proportional Percent', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 24, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Integral Percent', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 25, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Direvative Percent', 'configuration_id' => MACHINE_TRUETEMP_TCU, 'tag_id' => 26, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],

            [ 'name' => 'Capacity Utilization', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 2, 'type' => 'line', 'offset' => 0, 'divided_by' => 10 ],
            [ 'name' => 'Energy Consumption', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 3, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Drying hopper 1 inlet air temperature', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 9, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Drying hopper 1 set point', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 10, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Drying hopper 1 outlet air temperature', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 11, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Drying hopper 2 inlet air temperature', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 12, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Drying hopper 2 set point', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 13, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Drying hopper 2 outlet air temperature', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 14, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Drying hopper 3 inlet air temperature', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 15, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Drying hopper 3 set point', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 16, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Drying hopper 3 outlet air temperature', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 17, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Dew Point temperature', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 18, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Switch on DP setpoint', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 19, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Regen left air temperature', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 20, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Regen right air temperature', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 21, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Regen air set point', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 22, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Regen exhaust air temperature', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 23, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Bed-break set point', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 24, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Cool break set point', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 25, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Left bed in regen', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 26, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Left bed regen heating', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 27, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Left bed regen cooling', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 28, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Right bed in regen', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 29, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Right bed regen heating', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 30, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Right bed regen cooling', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 31, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Notification word', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 62, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Dryer hopper 1 heater PID percent', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 63, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Dryer hopper 2 heater PID percent', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 64, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Dryer hopper 3 heater PID percent', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 65, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Regen heater PID percent', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 66, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Left bed last regen heat time', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 67, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Right bed last regen heat time', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 68, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Left bed last regen cool time', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 69, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Right bed last regen cool time', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 70, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Drying hopper 1 status', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 33, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Drying hopper 2 status', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 34, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Drying hopper 3 status', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 35, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Dryer online', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 36, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Dryer sequenced shutdown', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 37, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'After cooler temperature', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 38, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Dirty filter bit', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 39, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Drying hopper 1 online hours - maint', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 40, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Drying hopper 1 online hours - total', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 41, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Drying hopper 2 online hours - maint', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 42, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Drying hopper 2 online total - total', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 43, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Drying hopper 3 online hours - maint', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 44, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Drying hopper 3 online hours - total', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 45, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Filter hours - maint', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 46, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Regen valve cycles - total', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 47, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Right bed regen cycles - total', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 48, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Left bed regen cycles - total', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 49, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Dryer online hours - maint', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 50, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Dryer online hours - total', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 51, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Process blower run hours - maint', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 52, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Process blower run hours - total', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 53, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Process valve cycles - total', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 54, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Power on hours - total', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 55, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Left regen heater hours - maint', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 56, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Left regen heater hours - total', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 57, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Right regen heater hours - maint', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 58, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Right regen heater hours - total', 'configuration_id' => MACHINE_NGX_DRYER, 'tag_id' => 59, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],

            [ 'name' => 'Capacity utilization', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 2, 'type' => 'line', 'offset' => 0, 'divided_by' => 10 ],
            [ 'name' => 'Energy consumption', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 3, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Drying hopper inlet air temperature', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 9, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Drying hopper set point', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 10, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Drying hopper outlet air temperature', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 11, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Dew point temperature', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 12, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Switch on DP setpoint', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 13, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Left regen air temperature', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 14, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Right regen air temperature', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 15, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Regen air set point', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 16, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Regen exhaust air temperature', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 17, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Bed-break set point', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 18, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Cool break set point', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 19, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Left bed in regen', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 20, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Left bed heating', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 21, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Left bed cooling', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 22, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Right bed in regen', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 23, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Right bed heating', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 24, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Right bed cooling', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 25, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Notification word', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 48, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Dryer hopper heater PID percent', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 49, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Regen heater PID percent', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 50, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Left bed last regen heat time', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 51, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Right bed last regen heat time', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 52, 'type' => 'line', 'offset' => 0, 'divided_by' => 1],
            [ 'name' => 'Left bed last regen cool time', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 53, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Right bed last regen cool time', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 54, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Drying hopper status', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 27, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Dryer online', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 28, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Dryer sequenced shutdown', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 29, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'After cooler temperature', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 30, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Dirty filter bit', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 31, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Filter hours - maint', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 32, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Left bed regen cycles - total', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 33, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Dryer online hours - maint', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 34, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Dryer online hours - total', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 35, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Process blower run hours - maint', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 36, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Process blower run hours - total', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 37, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Process valve cycles - total', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 38, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Power on hours - total', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 39, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Left regen heater hours - maint', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 40, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Left regen heater hours - total', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 41, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Right regen heater hours - maint', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 42, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Right regen heater hours - total', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 43, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Regen valve cycles - total', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 44, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Right bed regen cycles - total', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 45, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Convey status', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 55, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Machine loader blower run', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 56, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Hopper loader blower run', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 57, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Machine loader 1 status', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 58, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Machine loader 2 status', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 59, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Hopper loader status', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 60, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Machine loader 2 installed', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 61, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Machine loader 1 demand', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 62, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Machine loader 2 demand', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 63, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Hopper loader demand', 'configuration_id' => MACHINE_NGX_NOMAD_DRYER, 'tag_id' => 64, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],

            [ 'name' => 'Network run bit', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 1, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Cooling disabled', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 2, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Start mode', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 3, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'System is online', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 4, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Alarm active', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 5, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Compressor fault iput', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 6, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'High discharge pressure switch input', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 7, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Pump overload input', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 8, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Pump 2 flow switch input', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 9, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Pump 2 overload input', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 10, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Flow switch input', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 11, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Fan overload input', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 12, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Configurable ditial input', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 13, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Condenser differential pressure switch input', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 14, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Evaporator differential pressure switch input', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 15, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Compressor A output status', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 16, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Pump output status', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 17, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Liquid line solenoid output status', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 18, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Condenser fan output status', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 19, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Tank fill solenoid output status', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 20, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Compressor B output status', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 21, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Alarm output status', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 22, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Heater output status', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 23, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Chiller set point', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 77, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Chiller out temperature', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 80, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Chiller in temperature', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 81, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Discharge pressure', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 82, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Suction pressure', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 83, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Refrigerant suction temperature', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 84, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Process out temperature', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 85, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Pump pressure', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 86, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Chiller flow', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 87, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Condenser inlet temperature', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 88, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Tank level', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 89, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Refrigerant liquid temperature', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 90, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Water regulating valve / VFD output percent', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 91, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Hot gas output', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 92, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Approach temperature', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 93, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Saturated discharge temperature', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 94, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Saturated suction temperature', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 95, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Subcool temperature', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 96, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Superheat temperature', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 97, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Process in temperature', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 98, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Capacity utilization', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 105, 'type' => 'line', 'offset' => 0, 'divided_by' => 10 ],
            [ 'name' => 'Energy consumption', 'configuration_id' => MACHINE_GP_PORTABLE_CHILLER, 'tag_id' => 106, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],

            [ 'name' => 'Tank temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 1, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 1 approach temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 2, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 1 chil in temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 3, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 1 chil out temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 4, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 1 condenser inlet temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 5, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 1 discharge pressure', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 6, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 1 electronic expansion valve ouput percent', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 7, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 1 fan VFD / water cooled modulating valve output %', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 8, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 1 fluid flow', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 9, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 1 hot gas bypass percent', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 10, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 1 regrigerant liquid temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 11, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 1 regrigerant suction temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 12, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 1 saturated discharge temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 13, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 1 saturated suction temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 14, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 1 subcool temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 15, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 1 suction pressure', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 16, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 1 superheat temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 17, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 2 approach temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 18, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 2 chil in temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 19, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 2 chil out temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 20, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 2 condenser inlet temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 21, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 2  discharge pressure', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 22, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 2 electronic expansion valve ouput percent', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 23, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 2 fan VFD / water cooled modulating valve output %', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 24, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 2 fluid flow', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 9, 'type' => 'line', 'offset' => 25, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 2 hot gas bypass percent', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 26, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 2 regrigerant liquid temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 27, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 2 regrigerant suction temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 28, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 2 saturated discharge temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 29, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 2 saturated suction temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 30, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 2 subcool temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 31, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 2 suction pressure', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 32, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 2 superheat temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 33, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 3 approach temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' =>34, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 3 chil in temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 35, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 3 chil out temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 36, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 3 condenser inlet temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 37, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 3 discharge pressure', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 38, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 3 electronic expansion valve ouput percent', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 39, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 3 fan VFD / water cooled modulating valve output %', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 40, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 3 fluid flow', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 41, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 3 hot gas bypass percent', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 42, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 3 regrigerant liquid temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 43, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 3 regrigerant suction temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 44, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 3 saturated discharge temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 45, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 3 saturated suction temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 46, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 3 subcool temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 47, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 3 suction pressure', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 48, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 3 superheat temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 49, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 4 approach temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 50, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 4 chil in temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 51, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 4 chil out temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 52, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 4 condenser inlet temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 53, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 4 discharge pressure', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 54, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 4 electronic expansion valve ouput percent', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 55, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 4 fan VFD / water cooled modulating valve output %', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 56, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 4 fluid flow', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 57, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 4 hot gas bypass percent', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 58, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 4 regrigerant liquid temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 59, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 4 regrigerant suction temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 60, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 4 saturated discharge temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 61, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 4 saturated suction temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 62, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 4 subcool temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 63, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 4 suction pressure', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 64, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 4 superheat temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 65, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 5 approach temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 66, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 5 chil in temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 67, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 5 chil out temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 68, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 5 condenser inlet temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 69, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 5 discharge pressure', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 70, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 5 electronic expansion valve ouput percent', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 71, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 5 fan VFD / water cooled modulating valve output %', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 72, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 5 fluid flow', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 73, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 5 hot gas bypass percent', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 74, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 5 regrigerant liquid temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 75, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 5 regrigerant suction temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 76, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 5 saturated discharge temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 77, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 5 saturated suction temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 78, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 5 subcool temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 79, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 5 suction pressure', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 80, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 5 superheat temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 81, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 6 approach temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 82, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 6 chil in temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 83, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 6 chil out temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 84, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 6 condenser inlet temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 85, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 6 discharge pressure', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 86, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 6 electronic expansion valve ouput percent', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 87, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 6 fan VFD / water cooled modulating valve output %', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 88, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 6 fluid flow', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 89, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 6 hot gas bypass percent', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 90, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 6 regrigerant liquid temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 91, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 6 regrigerant suction temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 92, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 6 saturated discharge temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 93, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 6 saturated suction temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 94, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 6 subcool temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 95, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 6 suction pressure', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 96, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 6 superheat temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 97, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 7 approach temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 98, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 7 chil in temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 99, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 7 chil out temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 100, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 7 condenser inlet temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 101, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 7 discharge pressure', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 102, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 7 electronic expansion valve ouput percent', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 103, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 7 fan VFD / water cooled modulating valve output %', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 104, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 7 fluid flow', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 105, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 7 hot gas bypass percent', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 106, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 7 regrigerant liquid temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 107, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 7 regrigerant suction temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 108, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 7 saturated discharge temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 109, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 7 saturated suction temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 110, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 7 subcool temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 111, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 7 suction pressure', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 112, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 7 superheat temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 113, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 8 approach temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 114, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 8 chil in temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 115, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 8 chil out temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 116, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 8 condenser inlet temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 117, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 8 discharge pressure', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 118, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 8 electronic expansion valve ouput percent', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 119, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 8 fan VFD / water cooled modulating valve output %', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 120, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 8 fluid flow', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 121, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 8 hot gas bypass percent', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 122, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 8 regrigerant liquid temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 123, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 8 regrigerant suction temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 124, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 8 saturated discharge temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 125, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 8 saturated suction temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 126, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 8 subcool temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 127, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 8 suction pressure', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 128, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 8 superheat temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 129, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 9 approach temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 130, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 9 chil in temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 131, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 9 chil out temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 132, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 9 condenser inlet temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 133, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 9 discharge pressure', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 134, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 9 electronic expansion valve ouput percent', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 135, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 9 fan VFD / water cooled modulating valve output %', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 136, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 9 fluid flow', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 137, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 9 hot gas bypass percent', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 138, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 9 regrigerant liquid temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 139, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 9 regrigerant suction temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 140, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 9 saturated discharge temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 141, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 9 saturated suction temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 142, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 9 subcool temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 143, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 9 suction pressure', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 144, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 9 superheat temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 145, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 10 approach temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 146, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 10 chil in temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 147, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 10 chil out temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 148, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 10 condenser inlet temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 149, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 10 discharge pressure', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 150, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 10 electronic expansion valve ouput percent', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 151, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 10 fan VFD / water cooled modulating valve output %', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 152, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 10 fluid flow', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 153, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 10 hot gas bypass percent', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 154, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 10 regrigerant liquid temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 155, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 10 regrigerant suction temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 156, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 10 saturated discharge temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 157, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 10 saturated suction temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 158, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 10 subcool temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 159, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 10 suction pressure', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 160, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Circuit 10 superheat temperature', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 161, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Network start', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 193, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'System online', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 194, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Alarm active', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 195, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Remote mode', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 196, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Chiller active temperature setpoint', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 197, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ],
            [ 'name' => 'Capacity utilization', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 230, 'type' => 'line', 'offset' => 0, 'divided_by' => 10 ],
            [ 'name' => 'Energy consumption', 'configuration_id' => MACHINE_HE_CENTRAL_CHILLER, 'tag_id' => 231, 'type' => 'line', 'offset' => 0, 'divided_by' => 1 ]
        ];

        DB::table('machine_tags')->insert($machine_tags);
    }
}
