<?php
/**
 * Define Helper
 */

// Role
define('ROLE_SUPER_ADMIN', 100);
define('ROLE_ACS_ADMIN', 1);
define('ROLE_ACS_MANAGER', 2);
define('ROLE_ACS_VIEWER', 3);
define('ROLE_CUSTOMER_ADMIN', 4);

define('MACHINE_BD_BATCH_BLENDER', 1);
define('MACHINE_ACCUMETER_OVATION_CONTINUOUS_BLENDER', 2);
define('MACHINE_GH_GRAVIMETRIC_EXTRUSION_CONTROL_HOPPER', 3);
define('MACHINE_GH_F_GRAVIMETRIC_ADDITIVE_FEEDER', 4);
define('MACHINE_VTC_PLUS_CONVEYING_SYSTEM', 5);
define('MACHINE_NGX_DRYER', 6);
define('MACHINE_NGX_NOMAD_DRYER', 7);
define('MACHINE_T50_CENTRAL_GRANULATOR', 8);
define('MACHINE_GP_PORTABLE_CHILLER', 9);
define('MACHINE_HE_CENTRAL_CHILLER', 10);
define('MACHINE_TRUETEMP_TCU', 11);
